jLocal = str(input("Ingresa el nombre del partido local: "))
jVisitante = str(input("Ingresa el nombre del partido visitante: "))
resul = str(input("resultado: "))
datos = (jLocal, jVisitante, resul)
print(f"{datos[0]} vs {datos[1]} quedaron {datos[2]}")
